displayName: x-real-ip-overwrite
type: middleware

import: github.com/aless3/x-real-ip-overwrite

summary: "override X-Real-IP header with another header, like CF-Connecting-iP"

testData:
  header-name: "CF-Connecting-IP"
